(function(g){var window=this;var I7=function(a){g.Y.call(this,{H:"button",ca:["ytp-offline-slate-button","ytp-button"],K:[{H:"div",M:"ytp-offline-slate-button-icon",K:["{{icon}}"]},{H:"div",M:"ytp-offline-slate-button-text",K:["{{text}}"]}]});this.C=a;this.A=this.o=null;this.hide();this.W("click",this.D,this)},Nya=function(a,b){!a.o&&b&&b.toggleButtonRenderer?a.o=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.o=null);
J7(a)},J7=function(a){if(a.o){if(a.o.isToggled){var b=a.o.toggledText?g.KP(a.o.toggledText):"";
a.update({text:b,icon:Oya(a.o.toggledIcon)})}else b=a.o.defaultText?g.KP(a.o.defaultText):"",a.update({text:b,icon:Oya(a.o.defaultIcon)});a.show()}else a.hide()},Oya=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.dE?{H:"div",ca:["ytp-icon","ytp-icon-notifications-none"]}:{H:"svg",R:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{H:"path",R:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.qE();default:return null}},K7=function(a){g.Y.call(this,
{H:"div",
M:"ytp-offline-slate",K:[{H:"div",M:"ytp-offline-slate-bar",K:[{H:"span",M:"ytp-offline-slate-icon",K:[g.dE?{H:"div",ca:["ytp-icon","ytp-icon-live-icon"]}:{H:"svg",R:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{H:"path",R:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{H:"circle",R:{cx:"12",cy:"12",r:"3"}}]}]},{H:"span",M:"ytp-offline-slate-buttons"},{H:"span",M:"ytp-offline-slate-messages",K:[{H:"div",M:"ytp-offline-slate-main-text",K:["{{maintext}}"]},{H:"div",M:"ytp-offline-slate-subtitle-text",K:["{{subtitletext}}"]}]}]},{H:"div",M:"ytp-offline-slate-final-day",K:[{H:"div",M:"ytp-offline-slate-final-day-line-1",K:["Dawn of"]},{H:"div",M:"ytp-offline-slate-final-day-line-2",K:["The Final Day"]},{H:"div",M:"ytp-offline-slate-final-day-line-3",K:["-24 Hours Remain-"]}]}]});
this.A=a;this.B=this.o=null;this.C=new g.ut(this.F,1E3,this);this.P(a,"presentingplayerstatechange",this.G);this.P(a,"livestatedata",this.D);this.hide();a=this.A.ga();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.D(a)},L7=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.KP(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.KP(b.mainText):"";a.update({maintext:b,subtitletext:d});g.S(a.element,"ytp-offline-slate-single-text-line",!d)}},N7=function(a){g.oX.call(this,a);
this.I=!1;this.J=0;this.G=!1;this.o=window.NaN;this.A=this.B=null;this.C=!1;this.F=null;this.L=-(new g.Bn).getTimezoneOffset();this.D=new g.eG(this);g.M(this,this.D);var b=this.g.ga();if(b.xa){var c=g.X(this.g);g.bN()?!c.experiments.g("live_fresca_v2")||!g.KN(c)&&g.JN(c)||(this.I=this.C=!0,this.F=new K7(this.g),g.M(this,this.F),g.NW(this.g,this.F.element,4),(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.A=b.playabilityStatus),this.A?(b=Pya(this.A.liveStreamability&&this.A.liveStreamability.liveStreamabilityRenderer))?
M7(this,b):M7(this,7500):M7(this,1E3)):g.tV(this.g.app.A,"html5.unsupportedlive","YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1")}this.D.P(a,"heartbeatparams",this.mK);this.D.P(a,"presentingplayerstatechange",this.nK);this.D.P(a,"videoplayerreset",this.zR);this.D.P(a,"crn_heartbeat",this.lK);this.C&&this.A&&Qya(this,this.A);b=new g.JR(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"});g.GW(a,[b])},Rya=function(a){a=a.g.ga();
return!!g.XP(a)&&!a.Cr},O7=function(a){var b=a.g.ga();
return Rya(a)?!!a.B:!!b.heartbeatToken},M7=function(a,b){if(!a.o&&a.I){var c=a.g.ga();
if(O7(a)||c.xa)void 0==b&&(b=a.G?a.C?7500:a.B?1E3*a.B.interval:a.g.ga().heartbeatInterval||6E4:1E3),a.o=g.IE((0,g.z)(a.AS,a),b)}},Qya=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=Pya(c),f=a.g.ga();
if(g.uW(a.g).kb()&&!g.eQ(f)&&!a.g.isPeggedToLive()&&!d)return e;var k=(d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint)&&d.videoId;if(k)return g.$1(a.g.app,k,void 0,void 0,!0,!0,d),e;if("OK"==b.status.toUpperCase()){if(!f.hlsvp&&!f.Yd||a.A&&c&&c.broadcastId!=a.A.liveStreamability.liveStreamabilityRenderer.broadcastId)return c={video_id:f.videoId},f.isLiveDestination&&(c.is_live_destination="1"),a.g.jo(c),e;g.KW(a.g,"heartbeat")}return e},Pya=function(a){var b=0;
a&&a.pollDelayMs&&(a=(0,window.parseInt)(a.pollDelayMs,10))&&(b=a);return b},P7=function(a,b,c){if(a.o){a.o=window.NaN;
a.J++;var d=a.g.ga();(d.heartbeatSoftFail?0:a.J>=(a.B?a.B.g:d.heartbeatRetries||5))?(b=b?"heartbeat.net":"heartbeat.servererror",d=(d=a.g.ga())&&d.xa?g.T("YTP_ERROR_STREAM_LICENSE_NOT_FOUND"):g.T("YTP_ERROR_LICENSE"),g.tV(a.g.app.A,b,d,c)):M7(a)}},Q7=function(a){a.J=0;
a.o&&(g.KE(a.o),a.o=window.NaN);a.G=!1},Sya=function(a){try{return g.xw(a)}catch(b){return null}};g.p(I7,g.Y);
I7.prototype.D=function(){this.A||(this.A=new g.PG(g.X(this.C).Kg));var a={context:g.KG(this.A.g)};if(this.o.isToggled){a.params=this.o.toggledServiceEndpoint.removeUpcomingEventReminderEndpoint.params;var b="notification/remove_upcoming_event_reminder"}else a.params=this.o.defaultServiceEndpoint.addUpcomingEventReminderEndpoint.params,b="notification/add_upcoming_event_reminder";var c={timeout:5E3};c.onError=(0,g.z)(this.B,this);c.Gd=(0,g.z)(this.B,this);g.LG(this.A,b,a,c);this.o.isToggled=!this.o.isToggled;
J7(this)};
I7.prototype.B=function(){this.o&&(this.o.isToggled=!this.o.isToggled,J7(this))};g.p(K7,g.Y);
K7.prototype.D=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.o=a;b.liveStreamOfflineSlateRenderer.canShowCountdown?this.F():L7(this,b.liveStreamOfflineSlateRenderer);var c=this.element;if(b&&b.liveStreamOfflineSlateRenderer&&b.liveStreamOfflineSlateRenderer.scheduledStartTime){var d=b.liveStreamOfflineSlateRenderer.scheduledStartTime-(0,g.F)()/1E3;d=86400>=d&&86340<d}else d=!1;g.S(c,"ytp-offline-slate-show-final-day",d);if(c=a&&a.liveStreamability&&
a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail){d=0;for(var e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage=
"";b.liveStreamOfflineSlateRenderer.actionButtons?(this.B||(this.B=new I7(this.A),this.B.za(this.sa["ytp-offline-slate-buttons"]),g.M(this,this.B)),Nya(this.B,b.liveStreamOfflineSlateRenderer.actionButtons[0])):this.B&&Nya(this.B,null);this.o=a}else this.o=null;this.G()};
K7.prototype.G=function(){var a=g.uW(this.A),b=this.A.ga(),c=b.xa&&(g.RQ(a)||g.W(a,2)||g.W(a,64));a=a.kb()&&!g.eQ(b)&&!this.A.isPeggedToLive(!0);c&&!a&&this.o&&"LIVE_STREAM_OFFLINE"==this.o.status.toUpperCase()?this.g||(this.show(),this.A.V("offlineslatestatechange")):this.g&&(this.hide(),this.A.V("offlineslatestatechange"))};
K7.prototype.F=function(){var a=this.o&&this.o.liveStreamability&&this.o.liveStreamability.liveStreamabilityRenderer&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.F)()/1E3),c=a.canShowCountdown&&(0,window.parseInt)(a.scheduledStartTime,10);!c||c<=b?(L7(this,a),this.C.stop()):(b=g.uX(c-b),L7(this,a,b),g.vt(this.C))}};
K7.prototype.X=function(){this.C.dispose();this.C=null;g.Y.prototype.X.call(this)};g.p(N7,g.oX);g.h=N7.prototype;g.h.X=function(){Q7(this);g.JW(this.g,"heartbeat");g.oX.prototype.X.call(this)};
g.h.lK=function(){this.I=!0;M7(this,2E3)};
g.h.mK=function(a){this.B=a;M7(this,2E3)};
g.h.nK=function(a){g.W(a.state,2)||g.W(a.state,64)?(Q7(this),this.C&&(this.I=!0,M7(this,1E3))):(g.W(a.state,1)||g.W(a.state,8))&&M7(this,2E3)};
g.h.zR=function(){3!==this.g.Wa()&&M7(this,2E3)};
g.h.AS=function(){var a=g.X(this.g),b=this.g.ga();var c=a.baseYtUrl;if(3==this.g.Wa())this.o=window.NaN;else if(g.W(g.uW(this.g),4))this.o=window.NaN;else if(O7(this)||b.xa){if(!Rya(this)||b.xa){var d="GET";var e=a.o;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.dg,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.forcedExperiments,utc_offset_minutes:this.L};(e=g.RP(b))&&(a.uloc=e);(e=this.g.vh().ingestionTime)&&
(a.ingestion_time=e);c=g.Ng(c+"heartbeat",a)}else d="GET",c=g.Ng(this.B.url,{request_id:g.EN()}),b.dg&&(c=g.Ng(c,{vvt:b.dg}),b.mdxEnvironment&&(c=g.Ng(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Ng(c,{access_token:b.oauthToken}));b.Rk&&(c=g.Ng(c,{internalipoverride:b.Rk}));b.innertubez&&(c=g.Ng(c,{innertubez:b.innertubez}));c=g.Ng(c,{cpn:b.clientPlaybackNonce});g.YE(c,{format:"RAW",method:d,timeout:3E4,Ub:(0,g.z)(this.FJ,this),onError:(0,g.z)(this.EJ,this),Gd:(0,g.z)(this.GJ,this),
withCredentials:!0})}else Q7(this)};
g.h.FJ=function(a){if(this.o){a=a.responseText;var b=Sya(a);if(b){this.g.va("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(Tya))?"0"==c[1]?0:1:-1;if(-1==c)P7(this,!1,"decode");else if(2!=c||O7(this))if(this.J=0,this.o=window.NaN,1==c){this.G=!1;b=this.g;c="YTP_ERROR_LICENSE";var d=Sya(a);d?a=d.reason||g.T(c):((a=a.match(Tya))&&(a=(0,window.parseInt)(a[1],10))&&(c=g.oQ(a)),a=g.T(c));g.tV(b.app.A,"heartbeat.stop",
a,void 0)}else this.G=!0,a=0,this.C&&b&&(a=Qya(this,b),this.g.V("livestatedata",b)),a?M7(this,a):M7(this);else Q7(this),this.G=!0}};
g.h.EJ=function(a){P7(this,!0,"net-"+a.status)};
g.h.GJ=function(){P7(this,!0,"timeout")};
g.h.kK=function(){return!!this.F&&this.F.g};
var Tya=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.WZ.heartbeat=N7;})(_yt_player);
