(function(){/*

SPF
(c) 2012-2016 Google Inc.
https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function n(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}
var p=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function ba(){};function q(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function ca(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function da(a,b){if(a.some)return a.some(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}
function ea(a,b){if(a.filter)return a.filter(b,void 0);var c=[];q(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}function fa(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;q(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function r(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};function t(a,b){return v[a]=b}var v=window._spf_state||{};window._spf_state=v;function w(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ha(a){return"[object String]"==Object.prototype.toString.call(a)}var ia=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function x(a,b){a=a.split(b);var c=1==a.length;return[a[0],c?"":b,c?"":a.slice(1).join(b)]};function ja(a){a.data&&ha(a.data)&&0==a.data.lastIndexOf("spf:",0)&&ka(a.data.substring(4))}function ka(a){var b=y[a];b&&(delete y[a],b())}function la(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function ma(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var na=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;la(a);window.postMessage("","*");ma(a);return b}(),y={};"async-defers"in v||t("async-defers",y);y=v["async-defers"];na&&("async-listener"in v&&ma(v["async-listener"]),la(ja),t("async-listener",ja));var oa={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},z={};"config"in v||t("config",z);z=v.config;function pa(a){var b=A();a in b&&delete b[a]}function qa(){var a=A();for(b in a)ra(a[b])||delete a[b];a=A();var b=parseInt(z["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e;for(e in a)if(a[e].count<d){var f=e;d=a[e].count}delete a[f]}}function ra(a){if(!(a&&"data"in a))return!1;var b=a.life;b=isNaN(b)?Infinity:b;a=a.time;return p()-a<b}function sa(a){var b=parseInt(v["cache-counter"],10)||0;b++;t("cache-counter",b);a.count=b}
function A(a){return!a&&"cache-storage"in v?v["cache-storage"]:t("cache-storage",a||{})};function ta(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function ua(a,b){if(b){if(a.classList)return a.classList.contains(b);a=ta(a);return da(a,function(a){return a==b})}return!1}function B(a,b){b&&(a.classList?a.classList.add(b):ua(a,b)||(a.className+=" "+b))}function C(a,b){if(b)if(a.classList)a.classList.remove(b);else{var c=ta(a);c=ea(c,function(a){return a!=b});a.className=c.join(" ")}};function va(a){var b=document.body;b.dataset?b.dataset.spfName=a:b.setAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase(),a)};function wa(a,b){b=b||document;return b.querySelectorAll?b.querySelectorAll(a):[]}function xa(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}function ya(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function za(a,b,c){var d=null,e=window.history.state;if(e){d={};for(var f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];Aa(!0,a,d,c)}function Aa(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=p();t("history-timestamp",e);c["spf-timestamp"]=e;if(a)Ba(c,b);else if(a=Ca().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");t("history-url",b);d&&(d=v["history-callback"])&&d(b,c)}}
function Da(a){var b=window.location.href;if(v["history-ignore-pop"])t("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==v["history-url"]?(t("history-timestamp",c),Ba(a,b)):(a["spf-back"]=c<parseInt(v["history-timestamp"],10),a["spf-current"]=v["history-url"],t("history-timestamp",c),t("history-url",b),(c=v["history-callback"])&&c(b,a))}}
function Ba(a,b){var c=Ca().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function Ca(){var a=document.getElementById("history-iframe");a||(a=ya("history-iframe"));return a};function Ea(a,b){a&&b&&(a in E||(E[a]=[]),E[a].push(b))}function Fa(a,b){a in E&&b&&ca(E[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function Ha(a){a in E&&q(E[a],function(a,c,d){d[c]=null;a&&a()})}var E={};"ps-s"in v||t("ps-s",E);E=v["ps-s"];function F(a,b,c){var d=G[a];return a&&b?(d||(d=G[a]={items:[],o:0,m:0,A:1}),d.items.push({D:b,B:c||0})):d&&d.items.length||0}function H(a,b){var c=G[a];if(c){var d=!!c.o||!!c.m;0<c.A&&(b||!d)&&Ia(a,b)}}function I(a){(a=G[a])&&a.A--}function J(a,b){var c=G[a];c&&(c.A++,H(a,b))}function Ja(a){var b=G[a];b&&(Ka(b),delete G[a])}function Ia(a,b){var c=G[a];if(c&&(Ka(c),0<c.A&&c.items.length)){var d=c.items[0];d&&(a=l(function(a,b){b();a()},null,l(Ia,null,a,b)),b?(c.items.shift(),a(d.D)):La(c,d,a))}}
function La(a,b,c){b.B?(c=l(c,null,ba),a.m=setTimeout(c,b.B),b.B=0):(a.items.shift(),c=l(c,null,b.D),(b=(b=z["advanced-task-scheduler"])&&b.addTask)?a.o=b(c):a.m=setTimeout(c,0))}function Ka(a){if(a.o){var b=z["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.o);a.o=0}a.m&&(clearTimeout(a.m),a.m=0)}var G={};function K(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function L(a,b){a=K(a);return b?a.href:x(a.href,"#")[0]}
function Ma(a,b){var c=x(a,"#");a=c[0];q(b,function(b){a=a.replace(new RegExp("([?&])"+b+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""})});w(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function Na(a){var b=z["advanced-persistent-parameters"]||"",c=x(a,"#");a=c[0];var d=-1!=a.indexOf("?")?"&":"?";return a+(b?d+b:"")+c[1]+c[2]};function Oa(a,b,c,d){var e="js"==a;b=M(a,b);var f=c||"^"+b,g=N(a,f),k;c&&(k=O[N(a,c)])&&b!=k&&(n(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:k}),e=k,delete O[N(a,c)],e&&delete P[N(a,e)],delete E[N(a,c)],Ea(g,l(Pa,null,a,c,k)));if((e=P[N(a,b)])&&f!=e){delete O[N(a,e)];delete P[N(a,b)];var h=N(a,e);h&&g&&h in E&&(E[g]=(E[g]||[]).concat(E[h]),delete E[h])}P[N(a,b)]=f;O[N(a,f)]=b;Ea(g,d);d=l(Qa,null,a);Q[N(a,b,void 0)]?(e&&f!=e&&(a=Ra(a,b))&&a.setAttribute("name",c||""),d()):(a=Sa(a,b,d,void 0,
void 0,k))&&c&&a.setAttribute("name",c)}function Ta(a,b){var c=O[N(a,b)];delete O[N(a,b)];c&&delete P[N(a,c)];delete E[N(a,b)];Pa(a,b,c)}function Pa(a,b,c){c&&(n("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Ua(a,c))}function Qa(a){var b=N(a,""),c;for(c in E)0==c.indexOf(b)&&ca(c.substring(b.length).split("|"),l(Va,null,a))&&Ha(c)}
function Sa(a,b,c,d,e,f){function g(){Q[N(a,b,e)]&&(Q[N(a,b,e)]=2);k&&m&&m.parentNode&&h==document&&m.parentNode.removeChild(m);c&&setTimeout(c,0);return null}var k="js"==a;b=M(a,b);Q[N(a,b,e)]=1;var h=d||document,m=h.createElement(k?"script":"link");if(!b)return g();d=R(b);m.className=N(a,d);"onload"in m?m.onerror=m.onload=g:m.onreadystatechange=function(){/^c|loade/.test(m.readyState)&&g()};d=h.getElementsByTagName("head")[0]||h.body;k?(m.async=!0,m.src=b,d.insertBefore(m,d.firstChild)):(m.rel=
"stylesheet",m.href=b,(f=f?Ra(a,f,d):null)?d.insertBefore(m,f):d.appendChild(m));return m}function Ua(a,b){b=M(a,b);var c=Ra(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);delete Q[N(a,b)]}function Ra(a,b,c){b=R(b);return wa("."+N(a,b),c)[0]}
function Wa(a){var b="js"==a,c=[];q(wa(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href;e=M(a,e);if(!Q[N(a,e,void 0)]){Q[N(a,e,void 0)]=2;var f=R(e);B(d,N(a,f));if(f=d.getAttribute("name"))P[N(a,e)]=f,O[N(a,f)]=e;c.push(d)}})}
function Xa(a,b,c){if(b&&(b=M(a,b),c||!Q[N(a,b,void 0)]))if(c&&"img"==a)Ya(b);else{var d=R(b),e=N(a,d),f=N(a,"prefetch");d=document.getElementById(f);if(!d)d=ya(f,null,function(a){a.title=f;H(f,!0)});else if(!c&&d.contentWindow.document.getElementById(e))return;a=l(Za,null,d,a,b,e,f);d.title?a():F(f,a)}}
function Za(a,b,c,d,e){var f="js"==b,g="css"==b;a=a.contentWindow.document;var k=a.getElementById(d);k&&k.parentNode.removeChild(k);f?(k=a.createElement("object"),$a?a.createElement("script").src=c:k.data=c,k.id=d,a.body.appendChild(k)):g?(k=Sa(b,c,null,a,e),k.id=d):(k=a.createElement("img"),$a&&(c=c+"#"+p()),k.src=c,k.id=d,a.body.appendChild(k))}function Ya(a){var b=new Image;$a&&(a=a+"#"+p());b.src=a}
function ab(a,b,c){var d="js"==a,e=O[N(a,c)],f=b.replace(/\s/g,"");f=f||"";for(var g=0,k=0,h=f.length;k<h;++k)g=31*g+f.charCodeAt(k),g%=4294967296;f="hash-"+g;O[N(a,c)]=f;!bb(a,f)&&(b=cb(a,b))&&(Q[N(a,f,void 0)]=2,b&&!d&&(d=R(f),b.className=N(a,d),b.setAttribute("name",c)),(e=e&&e[0])&&Ua(a,e))}
function cb(a,b){b=ia(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body;"js"==a?(a=document.createElement("script"),a.text=b,c.appendChild(a),c.removeChild(a)):(a=document.createElement("style"),c.appendChild(a),"styleSheet"in a?a.styleSheet.cssText=b:a.appendChild(document.createTextNode(b)));return a}
function M(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=v[c]||"";if(ha(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);"img"!=a&&(b=0>b.indexOf("."+a)?b+"."+a:b);b=L(b)}else 0==d&&(b=L(b))}return b}function N(a,b,c){return a+"-"+b+(c?"-"+c:"")}function R(a){return a?String(a).replace(/[^\w]/g,""):""}function bb(a,b){a=Q[N(a,b,void 0)];return""==b||2==a}function Va(a,b){b=O[N(a,b)];return void 0!=b&&bb(a,b)}var Q={},P={},O={},$a=-1!=navigator.userAgent.indexOf(" Trident/");
"rsrc-s"in v||t("rsrc-s",Q);Q=v["rsrc-s"];"rsrc-n"in v||t("rsrc-n",P);P=v["rsrc-n"];"rsrc-u"in v||t("rsrc-u",O);O=v["rsrc-u"];function db(a){a=r(a);q(a,function(a){Xa("img",a,!0)})};function eb(a,b,c){Oa("js",a,b,c)}function fb(a){Ta("js",a)}function gb(a,b){Sa("js",a,b)}function hb(a){a=r(a);q(a,function(a){Xa("js",a)})}function ib(a,b,c){a=r(a);a=ea(a,function(a){return!!a});var d=[];q(a,function(a){void 0==O[N("js",a)]&&d.push(a)});var e=!d.length;if(b){var f=ca(a,l(Va,null,"js"));e&&f?b():(a=N("js",a.sort().join("|")),Ea(a,b))}c&&!e&&c(d)}function jb(a,b){a=r(a);q(a,function(a){if(a){var b=S[a]||a;b=M("js",b);var c=O[N("js",a)];c&&b!=c&&kb(a)}});ib(a,b,lb)}
function lb(a){q(a,function(a){function b(){eb(e,a)}var d=T[a],e=S[a]||a;d?jb(d,b):b()})}function kb(a){a=r(a);q(a,function(a){var b=[],d;for(d in T){var e=T[d];e=r(e);q(e,function(c){c==a&&b.push(d)})}q(b,function(a){kb(a)});fb(a)})}function mb(a,b){ab("js",a,b)}function nb(a){cb("js",a)}var T={};"js-d"in v||t("js-d",T);T=v["js-d"];var S={};"js-u"in v||t("js-u",S);S=v["js-u"];function ob(a,b,c){Oa("css",a,b,c)}function pb(a,b){Sa("css",a,b)}function qb(a){a=r(a);q(a,function(a){Xa("css",a)})};function rb(a,b,c){if(b){b=[];var d=0;c&&(a+="\r\n");var e=a.indexOf("[\r\n",d);for(-1<e&&(d=e+3);-1<(e=a.indexOf(",\r\n",d));){var f=ia(a.substring(d,e));d=e+3;f&&b.push(JSON.parse(f))}e=a.indexOf("]\r\n",d);-1<e&&(f=ia(a.substring(d,e)),d=e+3,f&&b.push(JSON.parse(f)));f="";a.length>d&&(f=a.substring(d),c&&w(f,"\r\n")&&(f=f.substring(0,f.length-2)));b=sb(b);return{w:b,g:f}}a=JSON.parse(a);b=sb(r(a));return{w:b,g:""}}
function U(a,b,c,d){var e=c&&0==c.type.lastIndexOf("navigate",0),f=c&&c.reverse,g=c&&!!c.position,k=c&&c.j,h=b.name||"",m="process "+L(a),D=!z["experimental-process-async"];var u=0;b.timing||(b.timing={});b.title&&(document.title=b.title);e&&b.url&&L(b.url)!=L(window.location.href)&&za(b.url+window.location.hash);b.head&&(u=l(function(a,b){a=V(a);tb(a);ub(a);I(m);vb(a,function(){b.spfProcessHead=p();J(m,D)})},null,b.head,b.timing),u=F(m,u));b.attr&&(u=l(function(a,b){for(var c in a){var d=document.getElementById(c);
if(d){var e=void 0,f=a[c];for(e in f){var g=f[e];"class"==e?d.className=g:"style"==e?d.style.cssText=g:(d.setAttribute(e,g),"value"==e&&(d[e]=g))}}}b.spfProcessAttr=p()},null,b.attr,b.timing),u=F(m,u));var Z=b.body||{},vc=u,Ga;for(Ga in Z)u=l(function(a,b){if(a=document.getElementById(a)){!e||g||k||(t("nav-scroll-position",null),t("nav-scroll-url",null),window.scroll(0,0),k=!0,c&&(c.j=!0));var d=V(b);ub(d);var u=function(){I(m);vb(d,function(){J(m,D)})};b=z["animation-class"];wb&&ua(a,b)?(a=new xb(a,
d.html,b,h,!!f),I(m),H(a.key,!0),F(a.key,l(yb,null,a),0),F(a.key,l(zb,null,a),17),F(a.key,l(Ab,null,a),a.T),F(a.key,l(function(){u();J(m,D)},null),0),H(a.key)):(b=z["experimental-html-handler"])?(I(m),b(d.html,a,function(){u();J(m,D)})):(a.innerHTML=d.html,u())}},null,Ga,Z[Ga],b.timing),u=F(m,u);Z=u-vc;b.foot?(u=l(function(a,b,c){c&&(b.spfProcessBody=p());a=V(a);ub(a);I(m);vb(a,function(){b.spfProcessFoot=p();J(m,D)})},null,b.foot,b.timing,Z),u=F(m,u)):Z&&(u=l(function(a){a.spfProcessBody=p()},null,
b.timing),u=F(m,u));d&&(u=F(m,l(d,null,a,b)));H(m,D)}function Bb(a,b,c,d){c="preprocess "+L(a);if(b.head){var e=l(function(a){a=V(a);tb(a);Cb(a);Db(a)},null,b.head);F(c,e)}var f=b.body||{},g;for(g in f)f[g]&&(e=l(function(a,b){a=V(b);Cb(a);Db(a)},null,g,f[g]),F(c,e));b.foot&&(e=l(function(a){a=V(a);Cb(a);Db(a)},null,b.foot),F(c,e));d&&F(c,l(d,null,a,b));H(c)}
function yb(a){B(a.a,a.s);B(a.a,a.H);B(a.a,a.K);B(a.a,a.I);B(a.a,a.J);a.l=document.createElement("div");a.l.className=a.S;var b=a.a,c=a.l;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.f=document.createElement("div");a.f.className=a.R;a.f.innerHTML=a.P;a.reverse?(b=a.l,b.parentNode.insertBefore(a.f,b)):(b=a.l,b.parentNode.insertBefore(a.f,b.nextSibling))}function zb(a){C(a.a,a.I);C(a.a,a.J);B(a.a,a.F);B(a.a,a.G)}
function Ab(a){a.a.removeChild(a.l);var b=a.f,c,d=b.parentNode;if(d&&11!=d.nodeType)if(b.removeNode)b.removeNode(!1);else{for(;c=b.firstChild;)d.insertBefore(c,b);d.removeChild(b)}C(a.a,a.F);C(a.a,a.G);C(a.a,a.H);C(a.a,a.K);C(a.a,a.s)}function sb(a){q(r(a),function(a){if(a){a.head&&(a.head=V(a.head));if(a.body)for(var b in a.body)a.body[b]=V(a.body[b]);a.foot&&(a.foot=V(a.foot))}});return a}
function V(a){var b=new Eb;if(!a)return b;if(!ha(a))return a.scripts&&q(a.scripts,function(a){b.scripts.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&q(a.styles,function(a){b.styles.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&q(a.links,function(a){"spf-preconnect"==a.rel&&b.links.push({url:a.url||"",rel:a.rel||""})}),b.html=a.html||"",b;a=a.replace(Fb,function(a,d,e,f){if("script"==d){d=(d=e.match(Gb))?d[1]:"";var c=e.match(Hb);c=c?c[1]:"";
var k=Ib.test(e);e=Jb.exec(e);return(e=!e||-1!=e[1].indexOf("/javascript")||-1!=e[1].indexOf("/x-javascript")||-1!=e[1].indexOf("/ecmascript"))?(b.scripts.push({url:c,text:f,name:d,async:k}),""):a}return"style"==d&&(d=(d=e.match(Gb))?d[1]:"",e=Jb.exec(e),e=!e||-1!=e[1].indexOf("text/css"))?(b.styles.push({url:"",text:f,name:d}),""):a});a=a.replace(Kb,function(a,d){var c=d.match(Lb);c=c?c[1]:"";return"stylesheet"==c?(c=(c=d.match(Gb))?c[1]:"",d=(d=d.match(Mb))?d[1]:"",b.styles.push({url:d,text:"",
name:c}),""):"spf-preconnect"==c?(d=(d=d.match(Mb))?d[1]:"",b.links.push({url:d,rel:c}),""):a});b.html=a;return b}function vb(a,b){if(0>=a.scripts.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.scripts.length){var e=a.scripts[c],f=function(){};e.url?f=e.name?l(eb,null,e.url,e.name):l(gb,null,e.url):e.text&&(f=e.name?l(mb,null,e.text,e.name):l(nb,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}
function Db(a){0>=a.scripts.length||(a=fa(a.scripts,function(a){return a.url}),hb(a))}function ub(a){0>=a.styles.length||q(a.styles,function(a){a.url?a.name?ob(a.url,a.name):pb(a.url):a.text&&(a.name?ab("css",a.text,a.name):cb("css",a.text))})}function Cb(a){0>=a.styles.length||(a=fa(a.styles,function(a){return a.url}),qb(a))}function tb(a){0>=a.links.length||(a=fa(a.links,function(a){return"spf-preconnect"==a.rel?a.url:""}),db(a))}
function xb(a,b,c,d,e){var f=parseInt(z["animation-duration"],10);this.a=a;this.P=b;this.T=f;this.reverse=e;b=document.body;b=(b.dataset?b.dataset.spfName:b.getAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase()))||"";f=parseInt(v.uid,10)||0;f++;this.key=a["spf-key"]||(a["spf-key"]=""+t("uid",f));this.H=b&&c+"-from-"+b;this.K=d&&c+"-to-"+d;this.l=null;this.S=c+"-old";this.f=null;this.R=c+"-new";this.s=c+(e?"-reverse":"-forward");this.I=c+"-start";this.J=this.s+"-start";this.F=c+"-end";
this.G=this.s+"-end"}function Eb(){this.html="";this.scripts=[];this.styles=[];this.links=[]}
var wb=function(){var a=document.createElement("div");return"transition"in a.style?!0:da(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})}(),Kb=/\x3clink([\s\S]*?)\x3e/ig,Fb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Ib=/(?:\s|^)async(?:\s|=|$)/i,Mb=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,Gb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Lb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,Hb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,Jb=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function Nb(a,b,c,d){var e=d||{},f=!1,g=0,k,h=new XMLHttpRequest;h.open(a,b,!0);h.timing={};var m=h.abort;h.abort=function(){clearTimeout(k);h.onreadystatechange=null;m.call(h)};h.onreadystatechange=function(){var a=h.timing;if(2==h.readyState){a.responseStart=a.responseStart||p();if("json"==h.responseType)f=!1;else if(-1<(h.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked"))f=!0;else{a=h.getResponseHeader("X-Firefox-Spdy");var c=window.chrome&&chrome.loadTimes&&chrome.loadTimes();
c=c&&c.wasFetchedViaSpdy;f=!(!a&&!c)}e.M&&e.M(h)}else 3==h.readyState?f&&e.u&&(a=h.responseText.substring(g),g=h.responseText.length,e.u(h,a)):4==h.readyState&&(a.responseEnd=a.responseEnd||p(),window.performance&&window.performance.getEntriesByName&&(h.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.u&&h.responseText.length>g&&(a=h.responseText.substring(g),g=h.responseText.length,e.u(h,a)),clearTimeout(k),e.L&&e.L(h))};"responseType"in h&&"json"==e.responseType&&(h.responseType=
"json");e.withCredentials&&(h.withCredentials=e.withCredentials);d="FormData"in window&&c instanceof FormData;a="POST"==a&&!d;if(e.headers)for(var D in e.headers)h.setRequestHeader(D,e.headers[D]),"content-type"==D.toLowerCase()&&(a=!1);a&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.O&&(k=setTimeout(function(){h.abort();e.N&&e.N(h)},e.O));h.timing.fetchStart=p();h.send(c);return h};function Ob(a,b){b=b||{};b.method=((b.method||"GET")+"").toUpperCase();b.type=b.type||"request";var c=a,d=z["url-identifier"]||"";if(d){d=d.replace("__type__",b.type||"");var e=x(c,"#"),f=x(e[0],"?");c=f[0];var g=f[1];f=f[2];var k=e[1];e=e[2];if(0==d.lastIndexOf("?",0))g&&(d=d.replace("?","&")),f+=d;else{if(0==d.lastIndexOf(".",0))if(w(c,"/"))d="index"+d;else{var h=c.lastIndexOf(".");-1<h&&(c=c.substring(0,h))}else w(c,"/")&&0==d.lastIndexOf("/",0)&&(d=d.substring(1));c+=d}c=c+g+f+k+e}d=L(c);c={};
c.spfUrl=d;c.startTime=p();c.fetchStart=c.startTime;g=Pb(a,b.current,null,b.type,!1);g=Qb(g,b.current);c.spfPrefetched=!!g&&"prefetch"==g.type;c.spfCached=!!g;if(g){a=l(Rb,null,a,b,c,g.key,g.response);b=window._spf_state=window._spf_state||{};var m=parseInt(b.uid,10)||0;m++;b=b.uid=m;y[b]=a;na?window.postMessage("spf:"+b,"*"):window.setTimeout(l(ka,null,b),0);return null}g={};if(f=z["request-headers"])for(m in f)k=f[m],g[m]=null==k?"":k;if(b.headers)for(m in b.headers)k=b.headers[m],g[m]=null==k?
"":k;null!=b.c&&(g["X-SPF-Referer"]=b.c);null!=b.current&&(g["X-SPF-Previous"]=b.current);if(m=z["advanced-header-identifier"])g["X-SPF-Request"]=m.replace("__type__",b.type),g.Accept="application/json";m=new Sb;f=l(Tb,null,a,b,c,m);a={headers:g,O:z["request-timeout"],M:l(Ub,null,a,m),u:l(Vb,null,a,b,c,m),L:f,N:f};b.withCredentials&&(a.withCredentials=b.withCredentials);z["advanced-response-type-json"]&&(a.responseType="json");return"POST"==b.method?Nb("POST",d,b.C,a):Nb("GET",d,null,a)}
function Rb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=p();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,z["cache-unified"]||(pa(d),f=!0));b.i&&"multipart"==e.type&&q(e.parts,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});Wb(a,b,c,e,f)}function Ub(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.f=-1!=a.toLowerCase().indexOf("multipart")}
function Vb(a,b,c,d,e,f,g){if(d.f){f=d.g+f;try{var k=rb(f,!0,g)}catch(h){e.abort();b.h&&b.h(a,h,e);return}b.i&&q(k.w,function(d){d.timing||(d.timing={});d.timing.spfCached=!!c.spfCached;d.timing.spfPrefetched=!!c.spfPrefetched;b.i(a,d)});d.a=d.a.concat(k.w);d.g=k.g}}
function Tb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var k in e.resourceTiming)g=e.resourceTiming[k],void 0!==g&&(w(k,"Start")||w(k,"End")||"startTime"==k)&&(c[k]=f+Math.round(g));"load"!=b.type&&(c.navigationStart=c.startTime);d.a.length&&
(d.g=ia(d.g),d.g&&Vb(a,b,c,d,e,"",!0));if("json"==e.responseType){if(!e.response){b.h&&b.h(a,Error("JSON response parsing failed"),e);return}var h=sb(r(e.response))}else try{h=rb(e.responseText).w}catch(D){b.h&&b.h(a,D,e);return}if(b.i&&1<h.length)for(d=d.a.length;d<h.length;d++)e=h[d],e.timing||(e.timing={}),e.timing.spfCached=!!c.spfCached,e.timing.spfPrefetched=!!c.spfPrefetched,b.i(a,e);if(1<h.length){var m;q(h,function(a){a.cacheType&&(m=a.cacheType)});h={parts:h,type:"multipart"};m&&(h.cacheType=
m)}else h=1==h.length?h[0]:{};Wb(a,b,c,h,!0)}function Wb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Pb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},g=parseInt(z["cache-lifetime"],10),k=parseInt(z["cache-max"],10);0>=g||0>=k||(k=A(),f={data:f,life:g,time:p(),count:0},sa(f),k[e]=f,setTimeout(qa,1E3))}d.timing=c;b.v&&b.v(a,d)}
function Pb(a,b,c,d,e){a=L(a);var f;z["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+K(b).pathname);return f||""}
function Qb(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+K(b).pathname));c.push(a);var d=null;da(c,function(a){a:{var b=A();if(a in b){b=b[a];if(ra(b)){sa(b);b=b.data;break a}pa(a)}b=void 0}b&&(d={key:a,response:b.response,type:b.type});return!!b});return d}function Sb(){this.f=!1;this.g="";this.a=[]};function Xb(a){return xa(a,function(a){return ua(a,z["link-class"])})}function Yb(a){return xa(a,function(a){return ua(a,z["nolink-class"])})}function Zb(a,b){return xa(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function $b(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Xb(a.target);return!b||z["nolink-class"]&&Yb(a.target)?null:(a=Zb(a.target,b))?a.href:null}function ac(a){return K(a).origin!=K(window.location.href).origin?!1:!0}
function bc(){if(!v["nav-init"])return!1;var a=parseInt(v["nav-counter"],10)||0;a++;var b=parseInt(z["navigate-limit"],10);b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(v["nav-init-time"],10);a--;a=p()-a;b=parseInt(z["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function cc(a,b){b=b||window.location.href;return-1!=a.indexOf("#")&&(a=L(a),b=L(b),a==b)?!1:!0}
function dc(a){if(!a.defaultPrevented){var b=$b(a);b&&(b=Na(b),ac(b)&&bc()&&n("spfclick",{url:b,target:a.target})&&(ec(b,{},new fc),a.preventDefault()))}}function gc(a){var b=$b(a);b&&setTimeout(function(){hc(b)},0)}function ic(){var a=v["nav-scroll-position"]||null;var b=v["nav-scroll-url"]||"";a=a&&b==window.location.href?a:null;jc();a&&window.scroll.apply(null,a)}
function kc(a,b){b=new fc({current:b&&b["spf-current"],history:!0,position:b&&b["spf-position"],c:b&&b["spf-referer"],reverse:!(!b||!b["spf-back"])});var c=z["reload-identifier"];c&&(a=Ma(a,[c]));ac(a)?bc()?n("spfhistory",{url:a,referer:b.c,previous:b.current})&&(b.position&&(t("nav-scroll-position",[window.pageXOffset,window.pageYOffset]),t("nav-scroll-url",window.location.href)),ec(a,{},b)):W(a,"1"):W(a,"9")}
function ec(a,b,c){lc();if(cc(a,c.current))if(mc(a,c.c,c.current,b)){t("nav-counter",(parseInt(v["nav-counter"],10)||0)+1);nc(a);var d=L(a),e="preprocess "+L(d);for(f in G)e!=f&&0==f.lastIndexOf("preprocess",0)&&Ja(f);d=oc()[d];t("nav-request",d);t("nav-promote",null);t("nav-promote-time",null);if(d&&4!=d.readyState)d="preprocess "+L(a),e="promote "+L(a),t("nav-promote",a),t("nav-promote-time",p()),Ja(d),H(e,!0),c.history||pc(a,c.c,l(X,null,b));else{d=l(X,null,b);e=l(qc,null,b,c);var f=l(rc,null,
b,c);z["advanced-navigate-persist-timing"]||sc();c.type="navigate";c.history&&(c.type+=c.reverse?"-back":"-forward");b=Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current,c:c.c});t("nav-request",b);c.history||pc(a,c.c,d)}}else W(a,"2");else c.history||pc(a,c.c,l(X,null,b)),tc(a,c)}
function tc(a,b){if(b.position)jc(),window.scroll.apply(null,b.position),b.j=!0;else if(a=x(a,"#"),a[2]){if(a=document.getElementById(a[2]))jc(),a.scrollIntoView(),b.j=!0}else b.j||(jc(),window.scroll(0,0),b.j=!0)}function pc(a,b,c){try{za(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),L(a,!0)!=window.location.href&&Aa(!1,a,{"spf-referer":b},void 0)}catch(d){lc(),c(a,d)}}function X(a,b,c,d){t("nav-request",null);uc(b,c,a,void 0,d)&&W(b,"10",c)}
function qc(a,b,c,d){if(wc(c,d,a))if(d.reload)W(c,"5");else if(d.redirect)xc(a,d.redirect);else try{U(c,d,b,function(){yc(c,d,a)})}catch(e){X(a,c,e)}else W(c,"3")}
function rc(a,b,c,d){t("nav-request",null);if(v["nav-promote"]==b.b){var e=d.timing||{};e.navigationStart=v["nav-promote-time"];e.spfPrefetched=!0}var f="multipart"==d.type;if(!f){if(!zc(c,d,a)){W(c,"4");return}if(d.reload){W(c,"5");return}if(d.redirect){xc(a,d.redirect);return}}try{U(c,f?{}:d,b,function(){var e=d.name||"";f&&q(d.parts,function(a){e=a.name||e});va(e);tc(c,b);Ac(c,d,a)})}catch(g){X(a,c,g)}}function xc(a,b){try{b+=window.location.hash,za(b,null,!0)}catch(c){lc(),X(a,b,c)}}
function lc(){var a=v["nav-request"];a&&(a.abort(),t("nav-request",null))}function Y(a,b){if(a){var c=Array.prototype.slice.call(arguments);c[0]=a;c=aa.apply(null,c)}return!1!==c}
function W(a,b,c){c=c?c.message:"";lc();nc();var d=b;c&&(d+=" Message: "+c);n("spfreload",{url:a,reason:d});var e=window.location.href;z["experimental-remove-history"]&&e==a&&(t("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=z["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);c=a;var k=x(c,"#");c=k[0];var h=-1!=c.indexOf("?")?"&":"?",m;for(m in d)c+=h+m,d[m]&&(c+="="+d[m]),h="&";a=c+k[1]+k[2]}window.location.href=a;cc(a,e)||window.location.reload()},0)}
function Bc(a,b,c){c.b=c.b||a;if(mc(a,void 0,void 0,b,!0)){var d=l(Cc,null,!1,b,c),e=l(Dc,null,!1,b,c),f=l(Ec,null,!1,b,c);c.type="load";Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,withCredentials:b.withCredentials})}}function hc(a,b){a=Na(a);Fc(a,b||{},new fc)}
function Fc(a,b,c){c.b=c.b||a;if(mc(a,void 0,void 0,b,!0)){var d=l(Cc,null,!0,b,c),e=l(Dc,null,!0,b,c),f=l(Ec,null,!0,b,c);c.type="prefetch";b=Ob(a,{method:b.method,headers:b.headers,i:e,h:d,v:f,C:b.postData,type:c.type,current:c.current});a=L(a);oc()[a]=b}}function Cc(a,b,c,d,e){a&&Gc(d);a&&v["nav-promote"]==c.b?X(b,d,e):uc(d,e,b,!0)}
function Dc(a,b,c,d,e){if(wc(d,e,b,!0)){if(e.reload){if(!a)return;if(v["nav-promote"]==c.b){W(d,"5");return}}if(e.redirect)Hc(a,b,c,e.redirect);else{if(a){var f=l(qc,null,b,c,d,e),g="promote "+L(c.b);F(g,f);if(v["nav-promote"]==c.b){H(g,!0);return}}(a?Bb:U)(d,e,c,function(){yc(d,e,b,!0)})}}}
function Ec(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!zc(d,e,b,!0)){W(d,"4");return}if(e.reload){if(!a)return;if(v["nav-promote"]==c.b){W(d,"5");return}}if(e.redirect){Hc(a,b,c,e.redirect);return}}var g="promote "+L(c.b);if(a){Gc(d);if(v["nav-promote"]==c.b){F(g,l(rc,null,b,c,d,e));H(g,!0);return}Ja(g)}g=a?Bb:U;try{g(d,f?{}:e,c,function(){Ac(d,e,b,!0)})}catch(k){Cc(a,b,c,d,k)}}
function Hc(a,b,c,d){a=a?Fc:Bc;var e={};q("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function uc(a,b,c,d,e){a={url:a,err:b,xhr:e};(c=Y((c||{}).onError,a))&&!d&&(c=n("spferror",a));return c}function mc(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Y((d||{}).onRequest,a))&&!e&&(d=n("spfrequest",a));return d}function wc(a,b,c,d){a={url:a,part:b};(c=Y((c||{}).onPartProcess,a))&&!d&&(c=n("spfpartprocess",a));return c}
function yc(a,b,c,d){a={url:a,part:b};Y((c||{}).onPartDone,a)&&!d&&n("spfpartdone",a)}function zc(a,b,c,d){a={url:a,response:b};(c=Y((c||{}).onProcess,a))&&!d&&(c=n("spfprocess",a));return c}function Ac(a,b,c,d){a={url:a,response:b};Y((c||{}).onDone,a)&&!d&&n("spfdone",a)}function Gc(a){a=L(a);var b=oc(),c=b[a];c&&c.abort();delete b[a]}function nc(a){var b=oc();a=a&&L(a);for(var c in b)a!=c&&Gc(c)}
var sc,Ic=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);sc=Ic?l(Ic,window.performance):ba;function oc(){return"nav-prefetches"in v?v["nav-prefetches"]:t("nav-prefetches",{})}function jc(){t("nav-scroll-position",null);t("nav-scroll-url",null)}
function fc(a){a=a||{};this.current=a.history&&a.current?a.current:window.location.href;this.history=!!a.history;this.b=a.b||"";this.position=a.position||null;this.c=void 0!=a.c?a.c:window.location.href;this.reverse=!!a.reverse;this.j=!!a.j;this.type=a.type||""};function Jc(){Wa("js");Wa("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Jc,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Jc))}document.addEventListener?document.addEventListener("DOMContentLoaded",Jc,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Jc);Jc();
var Kc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!Ca().contentWindow.history.pushState);a=a||{};for(var c in oa)z[c]=c in a?a[c]:oa[c];for(c in a)c in oa||(z[c]=a[c]);if(b){c=uc;if(!v["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",Da,!1);t("history-init",!0);t("history-callback",kc);t("history-error-callback",c);t("history-listener",Da);t("history-url",a);t("history-timestamp",p());var d={"spf-referer":document.referrer};
try{za(a,d)}catch(e){c&&c(a,e)}}!v["nav-init"]&&document.addEventListener&&(t("nav-init",!0),t("nav-init-time",p()),t("nav-counter",0),document.addEventListener("click",dc,!1),t("nav-listener",dc),!z["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",gc,!1),t("nav-mousedown-listener",gc)),document.addEventListener("scroll",ic,!1),t("nav-scroll-listener",ic))}return b},dispose:function(){"undefined"!=
typeof History&&History.prototype.pushState&&(lc(),v["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",v["nav-listener"],!1),document.removeEventListener("mousedown",v["nav-mousedown-listener"],!1),document.removeEventListener("scroll",v["nav-scroll-listener"],!1)),t("nav-listener",null),t("nav-mousedown-listener",null),t("nav-scroll-listener",null),t("nav-scroll-position",null),t("nav-scroll-url",null),t("nav-init",!1),t("nav-init-time",null),t("nav-counter",null)),
v["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",v["history-listener"],!1),t("history-init",!1),t("history-callback",null),t("history-error-callback",null),t("history-listener",null),t("history-url",null),t("history-timestamp",0)));for(var a in z)delete z[a]},navigate:function(a,b){a&&(a=Na(a),ac(a)?bc()?ec(a,b||{},new fc):W(a,"1"):W(a,"9"))},load:function(a,b){a=Na(a);Bc(a,b||{},new fc)},prefetch:hc,process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=
window.location.href;if("multipart"==a.type){a=a.parts;var e=a.length-1;q(a,function(a,b){U(d,a,null,l(c,null,b,e))})}else U(d,a,null,l(c,null,0,0))}},Lc={cache:{remove:pa,clear:function(){A({})}},script:{load:eb,get:gb,ready:ib,done:function(a){O[N("js",a)]="";Qa("js")},require:jb,declare:function(a,b){if(a){for(var c in a)T[c]=a[c];if(b)for(c in b)S[c]=b[c]}},path:function(a){t("rsrc-p-js",a)},unload:fb,ignore:function(a,b){a=r(a);a=N("js",a.sort().join("|"));Fa(a,b)},unrequire:kb,prefetch:hb},
style:{load:ob,get:pb,unload:function(a){Ta("css",a)},path:function(a){t("rsrc-p-css",a)},prefetch:qb}},global=this;global.spf=global.spf||{};var Mc=global.spf,Nc;for(Nc in Kc)Mc[Nc]=Kc[Nc];for(var Oc in Lc)for(var Pc in Lc[Oc])Mc[Oc]=Mc[Oc]||{},Mc[Oc][Pc]=Lc[Oc][Pc];n("spfready");}).call(this);
